# Generated by Django 6.0.2 on 2026-03-01 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=100)),
                ('categoria', models.CharField(choices=[('POP', 'Pop'), ('K-POP', 'K-Pop'), ('RAP', 'Rap'), ('J-POP', 'J-Pop'), ('INDIE', 'Indie'), ('SOUL MODERNO', 'Soul Moderno'), ('FOLK', 'Folk')], default='', max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/')),
                ('publicada', models.BooleanField(default=False)),
                ('data_fotografia', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
