# Generated by Django 6.0.2 on 2026-02-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('POP', 'Pop'), ('K-POP', 'K-Pop'), ('RAP', 'Rap'), ('J-POP', 'J-Pop'), ('INDIE', 'Indie'), ("SOUL MODERNO", "Soul Moderno"), ("FOLK", "Folk")], default='', max_length=100),
        ),
    ]
